name: pegadazero
region: nyc
features:
  - buildpack-stack=ubuntu-22

ingress:
  rules:
    - component:
        name: backend
      match:
        path:
          prefix: /api
    - component:
        name: frontend
      match:
        path:
          prefix: /

services:
  - name: backend
    environment_slug: docker
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 5000
    routes:
      - path: /api
    image:
      registry_type: DOCR
      repository: pegadazero-backend
      tag: latest
      deploy_on_push:
        enabled: true
    envs:
      - key: SQL_DATABASE_URL
        value: sqlite:////app/data/pegadazero.db
        type: GENERAL
        scope: RUN_TIME
      - key: KIWIFY_API_URL
        value: https://api.kiwify.com
        type: GENERAL
        scope: RUN_TIME
      - key: KIWIFY_API_KEY
        value: "<SET_IN_CONTROL_PANEL_OR_AS_SECRET>"
        type: SECRET
        scope: RUN_TIME

static_sites:
  - name: frontend
    environment_slug: html
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    github:
      repo: "<GITHUB_OWNER>/<REPO_NAME>"
      branch: main
      deploy_on_push: true
    source_dir: /
    build_command: npm ci && npm run build
    output_dir: dist
    envs:
      - key: VITE_API_URL
        value: "${APP_URL}/api"
        type: GENERAL
        scope: BUILD_TIME